name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      matrix:
        os: [ubuntu-20.04]
        dc:
          - dmd-2.096.1
          - dmd-2.095.0
          - ldc-1.26.0
          - ldc-1.20.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install package dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libclang-10-dev

      - uses: actions/setup-ruby@v1

      - run: gem install bundler -v 1.17.3

      - run: bundle install

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1.0.5
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test -q --build=unittest-cov
        env:
          LIBRARY_PATH: /usr/lib/llvm-10/lib

      - name: Build binary
        run: dub build -q
        env:
          LIBRARY_PATH: /usr/lib/llvm-10/lib

      - uses: codecov/codecov-action@v1
