name: CI
on: [push, pull_request]

jobs:
  test:
    name: Dub Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
        dc:
          - dmd-2.096.1
          - dmd-2.095.0
          - ldc-1.26.0
          - ldc-1.20.0
        arch:
          - x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true

      # Ruby puts this on the path which breaks ldc
      - name: Rename msys64/link.exe
        if: startsWith(matrix.os,'windows')
        shell: pwsh
        run: mv C:\msys64\usr\bin\link.exe C:\msys64\usr\bin\msys-link.exe

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Set LLVM Installation Path
        shell: pwsh
        run: |
          if ("${{ matrix.os }}" -like 'windows*') {
            $LLVM_PATH = "C:/Program Files/LLVM"
          } elseif ("${{ matrix.os }}" -like 'ubuntu*') {
            $LLVM_PATH = "${{ runner.temp }}/llvm"
          }
          echo "$LLVM_PATH" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$LLVM_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "LLVM_PATH=$LLVM_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Visual Studio Command Prompt - Windows
        if: startsWith(matrix.os,'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1.3.0
        with:
          version: 10
          directory: ${{ env.LLVM_PATH }}

      - name: Run tests
        run: dub test -q --build=unittest-cov --arch=${{ matrix.arch }}
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      - name: Build binary
        run: dub build -q --arch=${{ matrix.arch }}
        env:
          LIBRARY_PATH: "${{ env.LLVM_PATH }}/lib"

      - uses: codecov/codecov-action@v1
